---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ggomez1973/microservices
          searchPaths: /poc_comafi/config-properties
        # "native" se usa cuando esta el perfil activo para pruebas locales
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001
