---
spring:
  profiles: test
DBURL: jdbc:oracle://host1:33060/test_db

---
spring:
  profiles: integration
DBURL: jdbc:oracle://host2:33060/integration_db

---
spring:
  profiles: production
DBURL: mongodb://host2:33060/production_db
