---
spring:
  profile: test
DBURL: jdbc:mysql://host1:33060/test_db

spring:
  profile: integration
DBURL: jdbc:mysql://host2:33060/integration_db

spring:
  profile: production
DBURL: dynamodb://host2:33060/production_db
