---
spring:
  profile: test
DBURL: jdbc:oracle://host1:33060/test_db

spring:
  profile: integration
DBURL: jdbc:oracle://host2:33060/integration_db

spring:
  profile: production
DBURL: mongodb://host2:33060/production_db
