logging:
  level:
    root: ERROR
    org:
      springframework: ERROR
    com:
      ggomez:
        simplemq:
          conejo: DEBUG
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'